### ISSUE TITLE
Fonctionnement derrière un proxy : Redirection des appels à l'API

### ISSUE THREAD

**Issue by arnaudbirk** [ign-gpao/monitor#22]
Il faudrait que les appels du navigateur vers l'API passent systématiquement par le monitor, qui relaierai la réponse.

Cela permettrait de masquer complètement l'API de l'extérieur et de n'avoir à ouvrir qu'un port.

**Comment by IGNBPesty** [comment]
Confirmation du problème avec une installation chez Cégédim pour le projet LidarHD.
Le monitor est exposé sur une adresse, et l'API sur une autre (à la limite ce n'est pas nécessaire elle pourrait ne pas être exposée du tout) et l'interface du monitor génère des liens vers l'API qui ne fonctionnent pas.

**Comment by IGNBPesty** [comment]
Peut-être qu'il y a moyen d'utiliser le composant "http-proxy" (https://www.npmjs.com/package/http-proxy) pour que toutes les URLs en /api/ qui arrivent au monitor soient renvoyées sur le HOST/PORT de l'API.

**Comment by IGNBPesty** [comment]
Pour info, côté LIDARHD cette demande devient moins importante car on se sert de l'API en direct (ou via un client comme PostMan ou Insomnia) pour effectuer des actions sur les jobs. Mais ça resterait plus propre de masquer l'API de l'extérieur.
