### ISSUE TITLE
Les sessions à l'état "idle_requested" ne sont pas visible sur le monitor

### ISSUE THREAD

**Issue by IGNBPesty** [ign-gpao/monitor#94]
Dans le monitor, sur la page "hosts", j'ai passé le nombre de sessions à 0 via le bouton sur la droite. Comme sur la machine tous les threads étaient occupés à travailler les sessions sont passées à "idle_requested", mais sur la page hosts du monitor ça a affiché tout à 0 comme s'il n'y avait plus de threads existant.
Peut-être que dans la colonne "En veille" on peut faire la somme de "idle" + "idle_requested".

**Comment by ijeuffrard** [comment]
Bien vu, les sessions idle_requested sont dans état transitoire lorsqu'on coupe un thread qui etait en running, il finit son job puis passe en veille. Donc elles ont été rajoutées dans la colonne 'utilisée' = running+idle_requested
